### ISSUE TITLE
NodeJS version compatibility into package.json?

### ISSUE THREAD

**Issue by jpalala** [steelbrain/promise#6]
Though the package is built with for newer versions of node, it'd be best to put the minimum nodejs engine in the package.json, so it's clear in what version of node it'll work.

**Comment by jpalala** [comment]
Also according the code it will require from Dist, but I dont see the Dist folder - how does it work? thanks!

**Comment by steelbrain** [comment]
The dist folder is not visible in the git repo, it's there in the npm package.

I'll try to make sure this works on the ancient versions as well, but in the process I'll be renaming this to `sb-promise`

**Comment by jpalala** [comment]
I see, I didn't know before that it's possible to make a folder invisible to git, but available in the npm package.
